# Floodgateでは、岩盤プレーヤーのデータは暗号化されて送信されます
# 次の値は、生成されたキーFloodgateを指している必要があります。
# 間欠泉には公開鍵を使用し、水門には秘密鍵を使用する必要があります
key-file-name: key.pem

# Floodgateは、競合を回避するために、岩盤のユーザー名にプレフィックスを付加します
# ただし、特定の競合により一部のプラグインで問題が発生する可能性があるため、このプレフィックスは以下のプロパティを使用して構成できます
# ユーザー名が重複する可能性を回避するために、英数字を含まないプレフィックスを使用することをお勧めします。
# (日本語翻訳者追加文)初期設定では"."ですが"BE_"のほうがわかりやすいため変更しています。
username-prefix: "BE_"

# 岩盤のユーザー名のスペースを"_"に置き換える必要がありますか？
replace-spaces: true

# Floodgateのデフォルトロケール。 デフォルトでは、Floodgateはシステムロケールを使用します
# default-locale: en_US

disconnect:
  # 間欠泉ユーザーが接続時に受け取るはずの切断メッセージ
  # 無効なキーでサーバーに送信
  invalid-key: Please connect through the official Geyser
  # 間欠泉ユーザーが接続時に受け取るはずの切断メッセージ
  # 正しいキーでサーバーに送信されますが、正しいデータ形式では送信されません
  invalid-arguments-length: Expected {} arguments, got {}. Is Geyser up-to-date?

# プレーヤーリンクの構成
player-link:
  # リンクシステムを有効にするかどうか。 これをオフにすると、
  # すでにリンクされている場合でも、プレーヤーはリンク機能を使用できません。
  enabled: true

  # Whether to require a linked account in order to be able to join the server.
  require-link: false

  # 独自のリンクデータベースをホストする場合は、次のオプションをtrueに設定します。
  # -> これは、グローバルリンクに加えて機能します。
  # これを有効にする前に、リンクデータベースの実装をインストールする必要があることに注意してください。
  # そうしないとエラーが発生します。
  enable-own-linking: false

  # 次の3つのオプションは、「enable-own-linking」が「true」に設定されている場合にのみ適用されます。
  # /linkaccountおよび/unlinkaccountの使用を許可するかどうか
  # また、特定のユーザーがコマンドを使用できるようにすることもできます。
  # 権限floodgate.command.linkaccountおよびfloodgate.command.unlinkaccount。
  # これはリンク専用で、すでに接続されている人は接続されたままになります
  allowed: true
  # リンクコードが期限切れになるまでの時間（秒単位）。
  link-code-timeout: 300
  # 使用するプレーヤーリンクデータベースタイプ。 このオプションは、次の場合にのみ使用されます
  # 構成ディレクトリにある複数のデータベース実装です。
  type: sqlite

  # グローバルリンクを有効にするかどうか。 グローバルリンクは、人々がリンクできる中央サーバーです
  # アカウント（JavaおよびBedrock）を使用し、グローバルリンクが有効になっているサーバーに参加します。 の目標
  # グローバルリンクは、すべてのサーバーでアカウントをリンクする必要がないため、リンクを簡単にすることです。
  # -> サーバー固有のリンクデータベースは、グローバルリンクよりも優先されます。
  # グローバルリンクは通常、インターネットにアクセスできない場合、または次の場合にのみ無効にする必要があります
  # インターネットへのアクセスが制限されています。
  enable-global-linking: true

# これを変更しないでください
config-version: 2
